[package]
name = "i2csensors"
version = "0.1.3"
authors = ["martindeegan <mddeegan@gmail.com>"]
description = "Traits for I2C sensors."
repository = "https://github.com/martindeegan/i2cdev-sensors"
license = "MIT/Apache-2.0"

[dependencies]
