[package]
name = "i2cdev-lsm9ds0"
version = "0.1.0"
authors = ["martindeegan <mddeegan@gmail.com>"]

[lib]
name = "i2cdev_lms9ds0"
path =  "src/lib.rs"

[[bin]]
name = "lsm9ds0_bin"
path = "src/main.rs"

[dependencies]
i2cdev = "0.3.1"
byteorder = "1"
i2csensors = { path = "../i2csensors" }